# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('animal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('animal_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_protection_status', models.CharField(choices=[(b'LC', b'Least Concern'), (b'CD', b'Conservation Dependent'), (b'NT', b'Near Threatened'), (b'VU', b'Vulnerable'), (b'EN', b'Endangered'), (b'CR', b'Critically Endangered'), (b'EW', b'Extinct in the wild'), (b'EX', b'Extinct')], max_length=2)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Animals')),
            ],
        ),
    ]
